# Generated by Django 4.0.6 on 2022-07-27 13:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_me',
            name='title',
        ),
        migrations.AddField(
            model_name='about_me',
            name='Image1',
            field=models.ImageField(default=1, upload_to='about_me', verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_me',
            name='about_page',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Страница 'О нас'"),
        ),
    ]
