# Generated by Django 4.0.6 on 2022-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_remove_about_me_title_about_me_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='about_page',
            field=models.TextField(blank=True, null=True, verbose_name="Страница 'О нас'"),
        ),
    ]
