# Generated by Django 4.0.6 on 2022-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default=1, upload_to='about_me', verbose_name='contact_photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default=2, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
