# Generated by Django 4.0.6 on 2022-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_photo_contact_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(upload_to='contact', verbose_name='contact_photo'),
        ),
    ]
