# Generated by Django 4.0.6 on 2026-08-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('instagram_url', models.URLField(blank=True, max_length=255, verbose_name='Instagram URL')),
                ('github_url', models.URLField(blank=True, max_length=255, verbose_name='GitHub URL')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location / Working Hours')),
            ],
            options={
                'verbose_name': 'Site Contact Info',
                'verbose_name_plural': 'Site Contact Info',
            },
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Received At'),
        ),
    ]
