# Generated by Django 4.0.6 on 2022-07-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'intro', 'verbose_name_plural': 'intros'},
        ),
    ]
