# Generated by Django 4.0.6 on 2022-07-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_alter_intro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(upload_to='intro', verbose_name='Фото'),
        ),
    ]
