# Generated by Django 4.0.6 on 2022-08-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_rename_image_intro_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='source',
            new_name='image',
        ),
    ]
