# Generated by Django 4.0.6 on 2022-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_rename_source_intro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='icon',
            field=models.ImageField(default=1, upload_to='intro', verbose_name='icon'),
            preserve_default=False,
        ),
    ]
