# Generated by Django 4.0.6 on 2022-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_intro_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='icon',
            field=models.ImageField(upload_to='intro', verbose_name='icon1'),
        ),
    ]
