# Generated by Django 4.2.3 on 2023-07-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title2', models.CharField(max_length=250)),
                ('title3', models.CharField(max_length=250)),
                ('title4', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
