# Generated by Django 4.2.3 on 2023-09-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_options_home_decription_home_decription2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'setting '},
        ),
    ]
