# Generated by Django 6.0.6 on 2026-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('tech_tags', models.CharField(help_text='Comma separated e.g. Python, Django, PyTorch', max_length=255, verbose_name='Tech Stack Tags')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio', verbose_name='Project Thumbnail')),
                ('github_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='GitHub URL')),
                ('live_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Live Demo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
